# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decloak.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='decloak.proto',
  package='decloak',
  syntax='proto3',
  serialized_pb=_b('\n\rdecloak.proto\x12\x07\x64\x65\x63loak\"\x17\n\x08\x46\x65tchURL\x12\x0b\n\x03URL\x18\x01 \x01(\t\"\xfa\x01\n\x07WebPage\x12\x0b\n\x03URL\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x30\n\tredirtype\x18\x04 \x01(\x0e\x32\x1d.decloak.WebPage.RedirectType\x12\x10\n\x08redirURL\x18\x05 \x01(\t\x12(\n\x07headers\x18\x06 \x03(\x0b\x32\x17.decloak.WebPage.KeyVal\x12\x0c\n\x04\x62ody\x18\x07 \x01(\t\x1a\"\n\x06KeyVal\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\t\"\"\n\x0cRedirectType\x12\x08\n\x04HTTP\x10\x00\x12\x08\n\x04\x42ODY\x10\x01\x32\x42\n\nFetchProxy\x12\x34\n\tfetchPage\x12\x11.decloak.FetchURL\x1a\x10.decloak.WebPage\"\x00\x30\x01\x62\x06proto3')
)



_WEBPAGE_REDIRECTTYPE = _descriptor.EnumDescriptor(
  name='RedirectType',
  full_name='decloak.WebPage.RedirectType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HTTP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BODY', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=268,
  serialized_end=302,
)
_sym_db.RegisterEnumDescriptor(_WEBPAGE_REDIRECTTYPE)


_FETCHURL = _descriptor.Descriptor(
  name='FetchURL',
  full_name='decloak.FetchURL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='URL', full_name='decloak.FetchURL.URL', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=49,
)


_WEBPAGE_KEYVAL = _descriptor.Descriptor(
  name='KeyVal',
  full_name='decloak.WebPage.KeyVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='decloak.WebPage.KeyVal.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val', full_name='decloak.WebPage.KeyVal.val', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=266,
)

_WEBPAGE = _descriptor.Descriptor(
  name='WebPage',
  full_name='decloak.WebPage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='URL', full_name='decloak.WebPage.URL', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='decloak.WebPage.status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reason', full_name='decloak.WebPage.reason', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='redirtype', full_name='decloak.WebPage.redirtype', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='redirURL', full_name='decloak.WebPage.redirURL', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='headers', full_name='decloak.WebPage.headers', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='decloak.WebPage.body', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_WEBPAGE_KEYVAL, ],
  enum_types=[
    _WEBPAGE_REDIRECTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=302,
)

_WEBPAGE_KEYVAL.containing_type = _WEBPAGE
_WEBPAGE.fields_by_name['redirtype'].enum_type = _WEBPAGE_REDIRECTTYPE
_WEBPAGE.fields_by_name['headers'].message_type = _WEBPAGE_KEYVAL
_WEBPAGE_REDIRECTTYPE.containing_type = _WEBPAGE
DESCRIPTOR.message_types_by_name['FetchURL'] = _FETCHURL
DESCRIPTOR.message_types_by_name['WebPage'] = _WEBPAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FetchURL = _reflection.GeneratedProtocolMessageType('FetchURL', (_message.Message,), dict(
  DESCRIPTOR = _FETCHURL,
  __module__ = 'decloak_pb2'
  # @@protoc_insertion_point(class_scope:decloak.FetchURL)
  ))
_sym_db.RegisterMessage(FetchURL)

WebPage = _reflection.GeneratedProtocolMessageType('WebPage', (_message.Message,), dict(

  KeyVal = _reflection.GeneratedProtocolMessageType('KeyVal', (_message.Message,), dict(
    DESCRIPTOR = _WEBPAGE_KEYVAL,
    __module__ = 'decloak_pb2'
    # @@protoc_insertion_point(class_scope:decloak.WebPage.KeyVal)
    ))
  ,
  DESCRIPTOR = _WEBPAGE,
  __module__ = 'decloak_pb2'
  # @@protoc_insertion_point(class_scope:decloak.WebPage)
  ))
_sym_db.RegisterMessage(WebPage)
_sym_db.RegisterMessage(WebPage.KeyVal)



_FETCHPROXY = _descriptor.ServiceDescriptor(
  name='FetchProxy',
  full_name='decloak.FetchProxy',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=304,
  serialized_end=370,
  methods=[
  _descriptor.MethodDescriptor(
    name='fetchPage',
    full_name='decloak.FetchProxy.fetchPage',
    index=0,
    containing_service=None,
    input_type=_FETCHURL,
    output_type=_WEBPAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FETCHPROXY)

DESCRIPTOR.services_by_name['FetchProxy'] = _FETCHPROXY

# @@protoc_insertion_point(module_scope)
